_target_: plmr.models.modules.peint_module.PEINTModule

net: ${net}
weight_decay: 0.01

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001

scheduler:
  _target_: transformers.get_polynomial_decay_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 10000
  num_training_steps: 100000
  power: 2.0

compile: false
