_target_: peint.models.nets.peint.PEINT

evo_vocab: ${vocab}

enc_model:
  _target_: peint.models.nets.peint.ESMEncoder.from_pretrained
  finetune: false
  embed_x_per_chain: false
  ckpt_path: null

num_chains: 2
num_heads: 20
embed_dim: 640
max_len: 1022
num_encoder_layers: 3
num_decoder_layers: 3

dropout_p: 0.0
chain_break_token: .
use_chain_embedding: true
use_attention_bias: true
causal_decoder: true
