defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - lr_monitor
  - tqdm_progress_bar
  - grad_norm
  # - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1

lr_monitor:
  log_momentum: False
  log_weight_decay: False
  logging_interval: "epoch"
